// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMaIsLW3BYkLD0O_ABAF3qBZy5P7cjEWA',
    appId: '1:275185750466:web:cde2dd8bfb93476a1c865b',
    messagingSenderId: '275185750466',
    projectId: 'cross-website-83900',
    authDomain: 'cross-website-83900.firebaseapp.com',
    storageBucket: 'cross-website-83900.firebasestorage.app',
    measurementId: 'G-EXJ822Q2DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlPSsd66K4GlvfRUxg0mlwfnD0kY4t13M',
    appId: '1:275185750466:android:8f0fc9dd06c0dcc51c865b',
    messagingSenderId: '275185750466',
    projectId: 'cross-website-83900',
    storageBucket: 'cross-website-83900.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWcIE1y9P8aB1WLqOfZB3rQCRCL4YN66E',
    appId: '1:275185750466:ios:b9a8aa12ba49d5941c865b',
    messagingSenderId: '275185750466',
    projectId: 'cross-website-83900',
    storageBucket: 'cross-website-83900.firebasestorage.app',
    iosBundleId: 'com.example.crossWebsiteAdmin',
  );
}
