name: cross_website
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  jaspr: ^0.18.2
  jaspr_flutter_embed: ^0.4.5
  universal_web: ^1.1.0+2
  http: ^1.3.0
  jaspr_router: ^0.6.4
  lukehog_client: ^0.4.6

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.1.1
  jaspr_builder: ^0.18.2
  jaspr_lints: ^0.3.1
  lints: ^5.0.0
  jaspr_riverpod: ^0.3.19

jaspr:
  mode: static

