name: cross_website
description: A new jaspr project.
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  audioplayers: ^6.3.0
  csv: ^6.0.0
  emailjs: ^4.0.0
  highlight: ^0.7.0
  http: ^1.3.0
  jaspr: ^0.19.1
  jaspr_flutter_embed: ^0.4.5
  jaspr_router: ^0.7.0
  js_interop: ^0.0.1
  just_audio: ^0.10.4
  lukehog_client: ^0.4.6
  markdown: ^7.3.0
  record: ^6.0.0
  rxdart: ^0.28.0
  universal_web: ^1.1.0+2
  volume_controller: ^3.3.1
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.1.1
  jaspr_builder: ^0.19.1
  jaspr_lints: ^0.4.0
  jaspr_riverpod: ^0.3.19

jaspr:
  mode: static
