name: cross_website
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
     sdk: flutter
  jaspr: ^0.17.0
  jaspr_flutter_embed: ^0.4.3
  jaspr_router: ^0.6.1

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.1.0
  jaspr_builder: ^0.17.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  jaspr_lints: ^0.2.0

jaspr:
  mode: static

flutter:
  uses-material-design: true
