name: cross_website
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  audioplayers: ^6.3.0
  flutter:
     sdk: flutter
  flutter_sound: ^9.25.4
  flutter_svg: ^2.0.17
  jaspr: ^0.18.0
  jaspr_flutter_embed: ^0.4.5
  jaspr_router: ^0.6.3
  just_audio: ^0.9.46
  record: ^5.2.1
  rxdart: ^0.28.0
  volume_controller: ^3.3.1

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.1.1
  jaspr_builder: ^0.18.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  jaspr_lints: ^0.3.1

jaspr:
  mode: static

flutter:
  uses-material-design: true
